---
kind: pipeline
type: docker
name: publish

steps:
  - name: build
    image: node:current-alpine
    commands:
      - yarn global install hexo
      - yarn install
      - hexo clean && hexo generate
  - name: publish
    image: plugins/gh-pages
    settings:
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      pages_directory: public/

trigger:
  branch:
    - source