dictionaries:
  - en
  - en_GB
excluded_files:
  - "node_modules/**/*"
  - ".editorconfig"
  - ".eslintrc.js"
  - ".gitignore"
  - ".typo-ci.yml"
  - "LICENSE"
  - "netlify.toml"
  - "package.json"
  - "yarn.lock"
# excluded_words:
#   - example
spellcheck_filenames: false
